const levelOfSupportOptions = [
	{ value: 'essential', label: 'Essential: focused technical support', labelEs: 'Essential: soporte tecnico enfocado' },
	{ value: 'standard', label: 'Standard: technical help + creative guidance', labelEs: 'Standard: ayuda tecnica + guia creativa' },
	{ value: 'advanced', label: 'Advanced: deeper production / mix / identity support', labelEs: 'Advanced: apoyo mas profundo en produccion, mezcla o identidad' },
	{ value: 'full_direction', label: 'Full direction: sound, concept and artistic direction', labelEs: 'Full direction: sonido, concepto y direccion artistica' },
	{ value: 'not_sure', label: 'Not sure yet', labelEs: 'No estoy seguro todavia' },
];

const baseIdentityFields = [
	{ name: 'name', label: 'Name', labelEs: 'Nombre', type: 'text', placeholder: 'Your name', placeholderEs: 'Tu nombre', required: true },
	{ name: 'artist_name', label: 'Artist / Project Name', labelEs: 'Nombre artistico / proyecto', type: 'text', placeholder: 'Artist name, band or project', placeholderEs: 'Nombre artistico, banda o proyecto' },
	{ name: 'email', label: 'Email', labelEs: 'Correo', type: 'email', placeholder: 'your@email.com', placeholderEs: 'tu@email.com', required: true },
] as const;

const deadlineSupportFields = [
	{ name: 'deadline', label: 'Deadline', labelEs: 'Fecha limite', type: 'text', placeholder: 'Release date, target month or flexible', placeholderEs: 'Fecha de lanzamiento, mes objetivo o flexible' },
	{ name: 'level_of_support', label: 'Level of support', labelEs: 'Nivel de apoyo', type: 'select', options: levelOfSupportOptions, required: true },
] as const;

const notesConsentFields = [
	{ name: 'additional_notes', label: 'Additional notes', labelEs: 'Notas adicionales', type: 'textarea', placeholder: 'Anything else that would help understand the project.', placeholderEs: 'Cualquier otra cosa que ayude a entender el proyecto.' },
	{
		name: 'newsletter_consent',
		label: 'I agree to receive occasional FHUGAWZ Studio updates about music, production and artist projects.',
		labelEs: 'Acepto recibir actualizaciones ocasionales de FHUGAWZ Studio sobre musica, produccion y proyectos artisticos.',
		note: 'No noise. Only occasional notes when there is something worth sharing.',
		noteEs: 'Sin ruido. Solo notas ocasionales cuando haya algo que valga la pena compartir.',
		type: 'checkbox',
	},
] as const;

export const briefForms = {
	general: {
		serviceType: 'general',
		route: '/project-brief',
		title: 'General Project\nBrief',
		titleEs: 'Brief general\nde proyecto',
		kicker: 'FHUGAWZ STUDIO',
		kickerEs: 'FHUGAWZ STUDIO',
		description: 'Share the shape of the project, where it is now and what kind of result you want to build.',
		descriptionEs: 'Comparte la forma del proyecto, donde esta ahora y que tipo de resultado quieres construir.',
		pageKicker: 'PROJECT BRIEF',
		pageKickerEs: 'BRIEF DE PROYECTO',
		pageTitle: 'GENERAL PROJECT\nBRIEF',
		pageTitleEs: 'BRIEF GENERAL\nDE PROYECTO',
		pageDescription: 'A focused first signal for songs, releases and artist projects that need clearer direction.',
		pageDescriptionEs: 'Una primera senal enfocada para canciones, lanzamientos y proyectos artisticos que necesitan una direccion mas clara.',
		headerImage: undefined,
		headerImageAlt: undefined,
		fields: [
			...baseIdentityFields,
			{ name: 'country_city', label: 'Country / City', labelEs: 'Pais / ciudad', type: 'text', placeholder: 'Country and city', placeholderEs: 'Pais y ciudad' },
			{
				name: 'preferred_contact',
				label: 'Preferred contact method',
				labelEs: 'Metodo de contacto preferido',
				type: 'select',
				required: true,
				options: [
					{ value: 'email', label: 'Email' },
					{ value: 'whatsapp', label: 'WhatsApp' },
					{ value: 'instagram', label: 'Instagram' },
					{ value: 'other', label: 'Other', labelEs: 'Otro' },
				],
			},
			{
				name: 'requested_service',
				label: 'What are you looking for?',
				labelEs: 'Que estas buscando?',
				type: 'select',
				required: true,
				options: [
					{ value: 'demo_reconstruction', label: 'Demo Reconstruction', labelEs: 'Reconstruccion de demos' },
					{ value: 'music_production', label: 'Music Production', labelEs: 'Produccion musical' },
					{ value: 'mixing_mastering', label: 'Mixing / Mastering', labelEs: 'Mezcla / mastering' },
					{ value: 'artist_world_building', label: 'Artist World Building', labelEs: 'Desarrollo de universo artistico' },
					{ value: 'not_sure', label: 'Not sure yet', labelEs: 'No estoy seguro todavia' },
				],
			},
			{ name: 'project_stage', label: 'Current state of the project', labelEs: 'Estado actual del proyecto', type: 'textarea', required: true },
			{ name: 'main_problem', label: 'Main problem / what feels missing', labelEs: 'Problema principal / que se siente incompleto', type: 'textarea', required: true },
			{ name: 'references', label: 'References', labelEs: 'Referencias', type: 'textarea', placeholder: 'Songs, artists, visuals or worlds that feel close.', placeholderEs: 'Canciones, artistas, visuales o mundos que se sientan cercanos.' },
			{ name: 'material_links', label: 'Files / links', labelEs: 'Archivos / links', type: 'textarea', placeholder: 'Drive, Dropbox, SoundCloud, private links or notes.', placeholderEs: 'Drive, Dropbox, SoundCloud, links privados o notas.' },
			...deadlineSupportFields,
			{ name: 'desired_outcome', label: 'Desired outcome', labelEs: 'Resultado deseado', type: 'textarea', required: true },
			...notesConsentFields,
		],
	},
	demoReconstruction: {
		serviceType: 'demo_reconstruction',
		route: '/brief/demo-reconstruction',
		title: 'Demo\nReconstruction\nBrief',
		titleEs: 'Brief de\nreconstruccion\nde demo',
		kicker: 'DEMO RECONSTRUCTION',
		kickerEs: 'RECONSTRUCCION DE DEMO',
		description: 'Send the demo, what should survive from it and how open the reconstruction can be.',
		descriptionEs: 'Envia la demo, que deberia conservarse y que tan abierta puede ser la reconstruccion.',
		pageKicker: 'FHUGAWZ STUDIO',
		pageKickerEs: 'FHUGAWZ STUDIO',
		pageTitle: 'DEMO\nRECONSTRUCTION\nBRIEF',
		pageTitleEs: 'BRIEF DE\nRECONSTRUCCION\nDE DEMO',
		pageDescription: 'For rough demos, AI sketches and ideas that need to become original, directed productions.',
		pageDescriptionEs: 'Para demos crudas, bocetos de IA e ideas que necesitan convertirse en producciones originales y dirigidas.',
		headerImage: undefined,
		headerImageAlt: undefined,
		fields: [
			...baseIdentityFields,
			{
				name: 'ai_platform',
				label: 'AI platform or source',
				labelEs: 'Plataforma de IA o fuente',
				type: 'select',
				required: true,
				options: [
					{ value: 'suno', label: 'Suno' },
					{ value: 'udio', label: 'Udio' },
					{ value: 'other', label: 'Other', labelEs: 'Otra' },
					{ value: 'not_sure', label: 'Not sure', labelEs: 'No estoy seguro' },
				],
			},
			{ name: 'material_links', label: 'Current demo link', labelEs: 'Link de la demo actual', type: 'textarea', required: true },
			{ name: 'lyrics', label: 'Lyrics, if available', labelEs: 'Letra, si esta disponible', type: 'textarea' },
			{ name: 'keep_from_demo', label: 'What do you want to keep from the demo?', labelEs: 'Que quieres conservar de la demo?', type: 'textarea', required: true },
			{ name: 'main_problem', label: 'What feels artificial, weak, generic or unfinished?', labelEs: 'Que se siente artificial, debil, generico o inconcluso?', type: 'textarea', required: true },
			{
				name: 'creative_changes',
				label: 'Are creative changes allowed?',
				labelEs: 'Se permiten cambios creativos?',
				type: 'select',
				required: true,
				options: [
					{ value: 'close', label: 'Keep structure / melody / lyrics as close as possible', labelEs: 'Mantener estructura / melodia / letra lo mas cerca posible' },
					{ value: 'moderate', label: 'Allow moderate creative changes', labelEs: 'Permitir cambios creativos moderados' },
					{ value: 'full_reconstruction', label: 'Open to full creative reconstruction', labelEs: 'Abierto a una reconstruccion creativa completa' },
				],
			},
			{ name: 'references', label: 'References', labelEs: 'Referencias', type: 'textarea' },
			{ name: 'intended_release_format', label: 'Intended release format', labelEs: 'Formato de lanzamiento previsto', type: 'text', placeholder: 'Single, EP, album, pitch, private demo...', placeholderEs: 'Single, EP, album, pitch, demo privada...' },
			...deadlineSupportFields,
			...notesConsentFields,
		],
	},
	musicProduction: {
		serviceType: 'music_production',
		route: '/brief/music-production',
		title: 'Music Production\nBrief',
		titleEs: 'Brief de\nproduccion musical',
		kicker: 'MUSIC PRODUCTION',
		kickerEs: 'PRODUCCION MUSICAL',
		description: 'Tell me what exists now, what the song needs to feel like and what has to be built around it.',
		descriptionEs: 'Cuentame que existe ahora, como debe sentirse la cancion y que hay que construir alrededor.',
		pageKicker: 'FHUGAWZ STUDIO',
		pageKickerEs: 'FHUGAWZ STUDIO',
		pageTitle: 'MUSIC PRODUCTION\nBRIEF',
		pageTitleEs: 'BRIEF DE\nPRODUCCION MUSICAL',
		pageDescription: 'For demos, voice memos and rough ideas that need a complete production world.',
		pageDescriptionEs: 'Para demos, notas de voz e ideas crudas que necesitan un mundo de produccion completo.',
		headerImage: undefined,
		headerImageAlt: undefined,
		fields: [
			...baseIdentityFields,
			{ name: 'material_links', label: 'Current demo / voice memo / rough production', labelEs: 'Demo actual / nota de voz / produccion cruda', type: 'textarea', required: true },
			{ name: 'lyrics', label: 'Lyrics, if available', labelEs: 'Letra, si esta disponible', type: 'textarea' },
			{ name: 'project_stage', label: 'Current project stage', labelEs: 'Etapa actual del proyecto', type: 'textarea', required: true },
			{ name: 'emotion_story_atmosphere', label: 'Emotion / story / atmosphere', labelEs: 'Emocion / historia / atmosfera', type: 'textarea', required: true },
			{ name: 'references', label: 'Reference tracks', labelEs: 'Canciones de referencia', type: 'textarea' },
			{ name: 'existing_production_elements', label: 'Existing production elements', labelEs: 'Elementos de produccion existentes', type: 'textarea' },
			{ name: 'main_problem', label: 'What feels missing?', labelEs: 'Que se siente incompleto?', type: 'textarea', required: true },
			{ name: 'intended_release_format', label: 'Intended release format', labelEs: 'Formato de lanzamiento previsto', type: 'text' },
			...deadlineSupportFields,
			...notesConsentFields,
		],
	},
	mixingMastering: {
		serviceType: 'mixing_mastering',
		route: '/brief/mixing-mastering',
		title: 'Mixing / Mastering\nBrief',
		titleEs: 'Brief de mezcla\n/ mastering',
		kicker: 'MIXING / MASTERING',
		kickerEs: 'MEZCLA / MASTERING',
		description: 'Share the rough mix, stems and the problems the final sound needs to solve.',
		descriptionEs: 'Comparte la mezcla cruda, los stems y los problemas que el sonido final debe resolver.',
		pageKicker: 'FHUGAWZ STUDIO',
		pageKickerEs: 'FHUGAWZ STUDIO',
		pageTitle: 'MIXING / MASTERING\nBRIEF',
		pageTitleEs: 'BRIEF DE MEZCLA\n/ MASTERING',
		pageDescription: 'For finished productions that need final balance, impact and release-ready translation.',
		pageDescriptionEs: 'Para producciones terminadas que necesitan balance final, impacto y traduccion lista para lanzamiento.',
		headerImage: undefined,
		headerImageAlt: undefined,
		fields: [
			...baseIdentityFields,
			{ name: 'material_links', label: 'Current rough mix link', labelEs: 'Link de la mezcla cruda actual', type: 'textarea', required: true },
			{ name: 'stems_link', label: 'Stems or multitrack link', labelEs: 'Link de stems o multitrack', type: 'textarea', required: true },
			{ name: 'references', label: 'Reference tracks', labelEs: 'Canciones de referencia', type: 'textarea' },
			{
				name: 'main_concerns',
				label: 'Main concerns',
				labelEs: 'Preocupaciones principales',
				type: 'checkbox-group',
				required: true,
				options: [
					{ value: 'vocal_presence', label: 'Vocal presence', labelEs: 'Presencia vocal' },
					{ value: 'low_end', label: 'Low end', labelEs: 'Graves' },
					{ value: 'punch', label: 'Punch', labelEs: 'Golpe' },
					{ value: 'depth', label: 'Depth', labelEs: 'Profundidad' },
					{ value: 'stereo_image', label: 'Stereo image', labelEs: 'Imagen estereo' },
					{ value: 'loudness', label: 'Loudness', labelEs: 'Loudness' },
					{ value: 'darkness', label: 'Darkness', labelEs: 'Oscuridad' },
					{ value: 'clarity', label: 'Clarity', labelEs: 'Claridad' },
					{ value: 'translation', label: 'Translation', labelEs: 'Traduccion' },
				],
			},
			{ name: 'intended_release_format', label: 'Intended release format', labelEs: 'Formato de lanzamiento previsto', type: 'text' },
			...deadlineSupportFields,
			...notesConsentFields,
		],
	},
	artistWorldBuilding: {
		serviceType: 'artist_world_building',
		route: '/brief/artist-world-building',
		title: 'Artist World\nBuilding Brief',
		titleEs: 'Brief de universo\nartistico',
		kicker: 'ARTIST WORLD BUILDING',
		kickerEs: 'UNIVERSO ARTISTICO',
		description: 'Map the sound, visuals, references and next objective so the artist world can become clearer.',
		descriptionEs: 'Mapea sonido, visuales, referencias y siguiente objetivo para aclarar el universo artistico.',
		pageKicker: 'FHUGAWZ STUDIO',
		pageKickerEs: 'FHUGAWZ STUDIO',
		pageTitle: 'ARTIST WORLD\nBUILDING BRIEF',
		pageTitleEs: 'BRIEF DE UNIVERSO\nARTISTICO',
		pageDescription: 'For artists who need sound, visuals, story and release direction to speak the same language.',
		pageDescriptionEs: 'Para artistas que necesitan que sonido, visuales, historia y direccion de lanzamiento hablen el mismo idioma.',
		headerImage: undefined,
		headerImageAlt: undefined,
		fields: [
			...baseIdentityFields,
			{ name: 'artist_description', label: 'Short description of the artist/project', labelEs: 'Descripcion breve del artista/proyecto', type: 'textarea', required: true },
			{ name: 'material_links', label: 'Music links', labelEs: 'Links de musica', type: 'textarea' },
			{ name: 'references', label: 'Visual references', labelEs: 'Referencias visuales', type: 'textarea' },
			{ name: 'close_artists_projects', label: 'Artists/projects that feel close', labelEs: 'Artistas/proyectos que se sienten cercanos', type: 'textarea' },
			{ name: 'main_problem', label: 'What feels unclear or disconnected?', labelEs: 'Que se siente poco claro o desconectado?', type: 'textarea', required: true },
			{ name: 'existing_identity_links', label: 'Existing logo / cover / website / social profiles', labelEs: 'Logo / portada / web / perfiles sociales existentes', type: 'textarea' },
			{ name: 'next_objective', label: 'Next release or main objective', labelEs: 'Proximo lanzamiento u objetivo principal', type: 'textarea', required: true },
			...deadlineSupportFields,
			{ name: 'desired_outcome', label: 'Desired outcome', labelEs: 'Resultado deseado', type: 'textarea', required: true },
			...notesConsentFields,
		],
	},
} as const;
